---
title: "Carbon Chemestry FLK"
author: "Ana Palacio-Castro"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    fig_height: 8
    fig_width: 8
    df_print: paged
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
  knitr::opts_chunk$set(warning = FALSE, 
                        message = FALSE,
                        #options(knitr.kable.NA = ''),
                        fig.align = "center")
```

# Libraries and settings

```{r, include=FALSE}
# Libraries
    library(plyr)
    library(tidyverse)
    library(reshape2)
    library(ggthemes)
    library(lubridate)
    library(knitr)
    library(dplyr)
    library(broom)

# Interactive Maps
    library(leaflet)
```

# Import and format carbon chemestry data

```{r, include=FALSE}
# 1. Get data
CC.data<-read.csv("CC.data_normalized.csv", header = T)
  summary(CC.data)
  str((CC.data))
  #summary(CC.data$Region)
  #summary(CC.data$Location)
  Sites<-as.data.frame(unique(CC.data$SiteID))

# 2. Format variables
  # Date/times
  CC.data$Year<-as.numeric(CC.data$Year)
  CC.data$Date<-as.Date(CC.data$ESTDate, "%m/%d/%y")
 
  
  # Numerical data
  CC.data$Latitude <- gsub("N/A", "NA", CC.data$Latitude)
  CC.data$Longitude <- gsub("N/A", "NA", CC.data$Longitude)
  
  #Latitude_NA<-which(is.na(CC.data$Latitude))
  CC.data$Latitude <-as.numeric((as.character(CC.data$Latitude)))
  #Latitude_NA2<-which(is.na(CC.data$Latitude))
  #NewNAs<-setdiff(Latitude_NA2, Latitude_NA)
  #Row189 is not being recognized-fixed, it had an space
  
  #Longitude_NA<-which(is.na(CC.data$Longitude))
  CC.data$Longitude <-as.numeric((as.character(CC.data$Longitude)))
  #Longitude_NA2<-which(is.na(CC.data$Longitude))
  #NewNAs<-setdiff(Longitude_NA2, Longitude_NA)
  
  
  CC.data$Temperature_C <-
    as.numeric((as.character(CC.data$Temperature_C)))
  Temperature_NA2<-which(is.na(CC.data$Temperature_C))
  # 4 temp values not available in the original data
  
  CC.data$TA <-as.numeric((as.character(CC.data$TA)))
  #Row 730 does not have TA, pH, pCO2 or Aragonite 
  
  CC.data$DIC <-as.numeric((as.character(CC.data$DIC)))
  
  CC.data$pH <-as.numeric((as.character(CC.data$pH)))
  TA_NA<-which(is.na(CC.data$pH))
  # rows 31  32 663 664 730
  
  CC.data$pCO2 <-as.numeric((as.character(CC.data$pCO2)))
  CC.data$Aragonite_Sat_W<-
    as.numeric((as.character(CC.data$Aragonite_Sat_W)))
  
  CC.data$DIC[CC.data$DIC == 4574.590 ] <- NA
  
  #Remove Miami data
  #CC.data<-subset(CC.data,CC.data$Region!="SEFCRI")
  
  # #Get only FLK data#
  # FLK.data<-subset(CC.data,CC.data$Region=="FLK")
  
```

# Order seasons and months

```{r, include=FALSE}
CC.data$Season<-factor(CC.data$Season, levels = c(
                        "Winter", "Spring", "Summer", "Fall"))

CC.data$Month<-factor(CC.data$Month, levels = month.name)
#summary(CC.data$Month)

```


# Subste the data

```{r}
  #Get only FLK data#
  FLK.data<-subset(CC.data,CC.data$Region=="FLK")
  Metadata<-read.csv("Data/FLKLocations.csv", header = T)
  
  FLK.data<-join(FLK.data,Metadata, 
                 type = "left", by="SiteID")

```

# 1. Data available

## Locations (All samples)

```{r MapINformation, include=FALSE}
# Map information
# Add info from the sampling stations
Locations <- FLK.data %>% select(Latitude,
                                Longitude, 
                                Sub_region, 
                                SiteID)
Locations$GPS<-paste(Locations$Latitude,
                     "-", 
                     Locations$Longitude)

Locations<-unique(Locations)

GPS.Sites <- ddply (FLK.data, .(Sub_region, SiteID),summarise,
                Lat = mean (Latitude, na.rm = F), 
                Lon = mean (Longitude, na.rm = F),
                number = n())

#Change color depending on type of data?
  #stations$Site<-as.numeric(stations$Site)
  # pal <- colorNumeric(palette = "YlOrRd", 
                      #domain = stations$Site)
  
  #stations$Site<-as.factor(stations$Site)
  #pal.gen <- colorFactor(palette = "Set1",
  #                       domain = Locations$Location)
  pal.gen <- colorFactor(palette = "Set1",
                         domain = CC.data$Zone)
```


```{r makeAmap, echo=FALSE}
leaflet(FLK.data, height = '400px') %>% 
  addTiles() %>%
  addProviderTiles(providers$Esri.WorldImagery)%>%
  #addProviderTiles(providers$OpenStreetMap) %>% 
  #addMarkers(icon=coral.icon) %>% 
  addCircleMarkers(lng = ~Longitude, lat = ~Latitude, 
                   stroke = TRUE, 
                   radius = sqrt(GPS.Sites$number), 
                   fillOpacity = 1,
                   color = ~pal.gen(Zone),
                   label = ~SiteID,
                   labelOptions = labelOptions(
                     noHide = F, direction = "bottom",
                     textOnly = TRUE,
                     style = list(
        "color" = "white")))  %>%
  addLegend(position = "topright",
            pal = pal.gen, 
            values = ~Zone, opacity = 1) %>%
  fitBounds(lng1=-81.40, lat=26, lng2=-80.0, lat2=24)
  
```

Map of the sites were samples are collected