---
title: "4.TimeSeries"
author: "Ana Palacio-Castro"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    fig_height: 8
    fig_width: 8
    df_print: paged
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
  knitr::opts_chunk$set(warning = FALSE, 
                        message = FALSE,
                        #options(knitr.kable.NA = ''),
                        fig.align = "center")
```

# Libraries and settings

```{r, include=FALSE}
# Libraries
    library(plyr)
    library(tidyverse)
    library(reshape2)
    library(ggthemes)
    library(lubridate)
    library(knitr)
    library(dplyr)
    library(broom)
    library(zoo)

```

# 6. Walton Smith to detrend

## Create a regular data series
```{r}
# Get the WS data
dm<-WS.data %>% select(SiteID, Date, Year, Zone, Sub_region, Aragonite_Sat_W) 
dm<-subset(dm, Year>2013)

# Pool dates from the same month year
dm$Y_M<-as.yearmon(dm$Date, format="%Y-%m")

# How many samples per time point, zone and region
CasesS<-dm %>% count(Y_M,
                    Zone,
                    Sub_region,
                    sort = F)
CasesS

# Calculate average values per Zone and sub_region
dm_mean<-ddply (dm, .(Y_M, Zone,Sub_region),
                summarise,
                Amean = mean (Aragonite_Sat_W, na.rm = F))

# How many samples per time point, zone and region?
CasesP<-dm_mean %>% count(Y_M,
                    Zone,
                    Sub_region,
                    sort = T)
CasesP
ggplot(aes(x=Y_M,y=Amean), data=dm_mean)+geom_point()+geom_path()+geom_rug() + facet_grid(Sub_region~Zone)

# Create unique ID
dm_mean$ID<-paste(dm_mean$Sub_region,dm_mean$Zone, sep = "_" )
dm_mean<-select(dm_mean, Y_M, ID, Amean)


# Wide data to run multiple regul at once
head(dm_mean)
dm_mean<-reshape(dm_mean, idvar = "Y_M", timevar = "ID", direction = "wide")
#dm_mean$Day<-as.numeric(dm_mean$Y_M)

x<-select(dm_mean, Y_M)
x$Y_M<-as.numeric(x$Y_M)

y<-select(dm_mean, -Y_M)

# TIME SERIES 
library("pastecs")
# Use "regul" function to regularize your data series and then extract the new data
# Methods Linear (regul, by default)

regT<-regul(x=x$Y_M, y=y, n=36, units = "year", deltat=1/6)
plot(regT)
str(regT)

Mean_reg_WS<-extract(regT, n=15)
head(Mean_reg_WS)
plot(Mean_reg_WS[,1:8])
plot(Mean_reg_WS[,9:15])
autoplot(Mean_reg_WS)

# self-Mahalanobis distance for this multivariate series.
AutoD2(Mean_reg_WS,plotit=TRUE)

```

## Plot the raw ts data 
```{r}
#install.packages("tsbox")
library(tsbox)
df <- ts_df(Mean_reg_WS)
summary(df)
str(df)
head(df)
tail(df)
ggplot(aes(x=time, y=value), data=df)+geom_point()+geom_path() + facet_wrap(~id)


AResiduals<-(df$value -mean(df$value))
ComSum<-cumsum(AResiduals)
plot(df$time,ComSum)

```

## Decompose ts

```{r}
birthsComp <- decompose(Mean_reg_WS [, 1])
plot(birthsComp)
birthsSeasonAdj <- Mean_reg_WS [, 1] - birthsComp$seasonal
plot.ts(birthsSeasonAdj)

require(graphics)
head(Mean_reg_WS)


# Inshore
Biscayne_Inshore<-(stl (Mean_reg_WS[,1], "per", robust = TRUE))
acf(Biscayne_Inshore$time.series[,"remainder"])
plot(Biscayne_Inshore)
summary(Biscayne_Inshore)

UK_Inshore<-(stl (Mean_reg_WS[,2], "per", robust = TRUE))
plot(UK_Inshore)

MK_Inshore<-(stl (Mean_reg_WS[,3], "per"))
plot(MK_Inshore)

LK_Inshore<-(stl (Mean_reg_WS[,4], "per"))
plot(LK_Inshore)

#Mid Channel
Biscayne_MidCha<-(stl (Mean_reg_WS[,5], "per"))
plot(Biscayne_MidCha)

UK_MidCha<-(stl (Mean_reg_WS[,6], "per"))
plot(UK_MidCha)

MK_MidCha<-(stl (Mean_reg_WS[,7], "per"))
plot(MK_MidCha)

LK_MidCha<-(stl (Mean_reg_WS[,8], "per"))
plot(LK_MidCha)

#Off shore
Biscayne_Offshore<-(stl (Mean_reg_WS[,9], "per"))
plot(Biscayne_Offshore)

UK_Offshore<-(stl (Mean_reg_WS[,10], "per"))
plot(UK_Offshore)

MK_Offshore<-(stl (Mean_reg_WS[,11], "per"))
plot (MK_Offshore)

LK_Offshore<-(stl (Mean_reg_WS[,12], "per"))
plot (LK_Offshore)

# Oceanic
UK_Oceanic<-(stl (Mean_reg_WS[,13], "per"))
plot(UK_Oceanic)

MK_Oceanic<-(stl (Mean_reg_WS[,14], "per"))
plot(MK_Oceanic)

LK_Oceanic<-(stl (Mean_reg_WS[,15], "per"))
plot(LK_Oceanic)


# mark the 'outliers' :
(iO <- which(MK_Oceanic $ weights  < 1e-8)) # 10 were considered outliers
sts <- LK_Oceanic$time.series
points(time(sts)[iO], 0.8* sts[,"remainder"][iO], pch = 4, col = "red")
par(op)   # reset
# }
```



```{r}



# look the the seasonal component over 3 months and the trend over 4 years (play around with these ;)
xTstl <- stl(xT, s.window=13, t.window=30*5, robust=T, s.jump=1, t.jump=4, l.jump=1)

acf(xTstl$time.series[,"remainder"], lag.max=30*2)
plot(xTstl)
dTstl <- data.frame(date=date, data=xT, data.frame(xTstl$time.series))
dTstlm <- melt(dTstl, id.vars="date")
lastRecord <- dTstlm[dTstlm$date == max(dTstlm$date),]
pSTL <- ggplot(dTstlm) +
  # series
  geom_path(aes(x=date, y=value, colour=variable)) + 
  facet_grid(variable~., scale="free_y") +
  scale_colour_manual(guide="none", values=c("black", "#286a9a", "red", "Gray")) +
  # scale bar
  geom_segment(aes(x=date, xend=date, y=value, yend=value-0.5), data=lastRecord, size=4, alpha=0.5) +
  geom_text(aes(x=date, y=value-0.25), data=lastRecord, label="end", size=3, alpha=0.5, hjust=-0.22)

```


# 6. pCO2 

* By months (seasonality)

```{r}

pCO2_months<- ggplot(FLK.data,
                          aes(x=Month, y=pCO2)) +
  
  theme_bw() +
  #scale_y_continuous(limits = c(0,5.5),
  #                     name=("Aragonite Saturation") ,
  #                     breaks = seq(0, 5, 1),  
   #                    expand = c(0, 0)) +
  #scale_x_date(name="Date",
               #labels = date_format("%M/%Y"),
               #limits = c(-1,114),
   #            expand = c(0, 0),
    #           breaks ="6 months")+
  
geom_boxplot()+
geom_point(aes(fill=factor(Year)), shape=21, alpha=0.5, size=0.5)+ 
geom_abline(slope = 0, intercept = 3, color="gray", linetype=2)+
  
theme(legend.position=c(0.65, 0.05),
      legend.direction = "horizontal",
      legend.title = element_blank(),
          plot.background=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          )
  
pCO2_months  +  facet_wrap(Sub_region~.)
pCO2_months  +  facet_wrap(Zone~.)
pCO2_months  +  facet_grid(Zone~Sub_region)
```

* By years (trends) -> need to remove sites not sampled across timepoints

```{r}

pCO2_year<- ggplot(FLK.data,
                          aes(x=factor(Year), y=pCO2)) +
  
  theme_bw() +
  ylab("pCO2")+ xlab("Year")+ 
  #scale_y_continuous(limits = c(0,5.5),
  #                     name=("Aragonite Saturation") ,
  #                     breaks = seq(0, 5, 1),  
  #                     expand = c(0, 0)) +

  #scale_x_date(name="Date",
               #labels = date_format("%M/%Y"),
               #limits = c(-1,114),
   #            expand = c(0, 0),
    #           breaks ="6 months")+
  
geom_boxplot()+
geom_point(aes(fill=factor(Season)), shape=21, alpha=0.5)+ 
geom_abline(slope = 0, intercept = 3, color="gray", linetype=2)+
  
theme(legend.position=c(0.65, 0.1),
      legend.direction = "horizontal",
      legend.title = element_blank(),
          plot.background=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          ) +
  #scale_fill_gradient(low = "blue", high = "red", na.value = NA)+
  #scale_colour_gradientn(colours = terrain.colors(10))+
  #scale_fill_gradient2()+
  
  facet_wrap(Region~., scales= "free_y")
  
pCO2_year
#ggsave(file="Outputs/Aragonite.svg", plot=Aragonite, dpi = 300, width=6, height=4)

```


```{r}
  HighpCO2<-CC.data[FLK.data$pCO2 > 1000, ] 
```


# 8. pH 

* By months (seasonality)

```{r}

pH_months<- ggplot(FLK.data,
                          aes(x=Month, y=pH)) +
  
  theme_bw() +
  #scale_y_continuous(limits = c(0,5.5),
  #                     name=("Aragonite Saturation") ,
  #                     breaks = seq(0, 5, 1),  
   #                    expand = c(0, 0)) +
  #scale_x_date(name="Date",
               #labels = date_format("%M/%Y"),
               #limits = c(-1,114),
   #            expand = c(0, 0),
    #           breaks ="6 months")+
  
geom_boxplot()+
geom_point(aes(fill=factor(Year)), shape=21, 
           alpha=0.5, size=0.8)+ 
geom_abline(slope = 0, intercept = 3, color="gray", linetype=2)+
  
theme(legend.position=c(0.65, 0.05),
      legend.direction = "horizontal",
      legend.title = element_blank(),
          plot.background=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          ) +
  #scale_fill_gradient(low = "blue", high = "red", na.value = NA)+
  #scale_colour_gradientn(colours = terrain.colors(10))+
  #scale_fill_gradient2()+
  
  facet_wrap(Region~., scales = "free_y")
  
pH_months
```

* By years (trends) -> need to remove sites not sampled across timepoints

```{r}

pH_year<- ggplot(FLK.data,
                          aes(x=factor(Year), y=pH)) +
  
  theme_bw() +
  ylab("pH")+ xlab("Year")+ 
  #scale_y_continuous(limits = c(0,5.5),
  #                     name=("Aragonite Saturation") ,
  #                     breaks = seq(0, 5, 1),  
  #                     expand = c(0, 0)) +

  #scale_x_date(name="Date",
               #labels = date_format("%M/%Y"),
               #limits = c(-1,114),
   #            expand = c(0, 0),
    #           breaks ="6 months")+
  
geom_boxplot()+
geom_point(aes(fill=factor(Season)), shape=21, 
           alpha=0.5, size=0.8)+ 
geom_abline(slope = 0, intercept = 3, color="gray", linetype=2)+
  
theme(legend.position=c(0.65, 0.1),
      legend.direction = "horizontal",
      legend.title = element_blank(),
          plot.background=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          ) +
  facet_wrap(Region~., scales= "free_y")
  
pH_year

```
