---
title: "6.Cycles"
author: "Ana Palacio-Castro"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    fig_height: 8
    fig_width: 8
    df_print: paged
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
  knitr::opts_chunk$set(warning = FALSE, 
                        message = FALSE,
                        #options(knitr.kable.NA = ''),
                        fig.align = "center")
```

# Libraries and settings

```{r, include=FALSE}
# Libraries
    library(plyr)
    library(tidyverse)
    library(reshape2)
    library(ggthemes)
    library(lubridate)
    library(knitr)
    library(dplyr)
    library(broom)
```

## Omega 

```{r}

WS.data<-read.csv("WS.data.csv", header = T)
WS.data$Date<-as.Date(WS.data$Date)

Cycles<-WS.data %>% select(SiteID, Date, Zone, Sub_region, Month, Precipitation,
                           Aragonite_Sat_W, BestSalinity, nTA, nDIC, pH, pCO2) 

clycle<- ggplot(Cycles, aes(x=Date)) +
  
  theme_bw() +
  #scale_y_continuous(limits = c(0,5.5),
  #                     name=("Aragonite Saturation") ,
  #                     breaks = seq(0, 5, 1),  
   #                    expand = c(0, 0)) +
  scale_x_date(name="Date",
               #labels = date_format("%M/%Y"),
               #limits = c(-1,114),
               expand = c(0, 0),
              breaks ="6 months")+
  
theme(legend.position="top",
      legend.direction = "horizontal",
      legend.title = element_blank(),
          plot.background=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          ) +
  facet_wrap(Sub_region~.)

```



```{r}
Omega<-clycle  +  
  geom_smooth(aes(x=Date, y=(Aragonite_Sat_W), colour=Zone), span= 0.3, se=FALSE)+
  geom_point(aes(x=Date, y=Aragonite_Sat_W, fill=Precipitation), shape=21, alpha=0.5, size=1)+ 
  geom_abline(slope = 0, intercept = 3, color="gray", linetype=2)
Omega

```

```{r}
nTAcycle<-clycle  +  
  geom_smooth(aes(x=Date, y=nTA, colour=Zone), span= 0.3, se=FALSE)+
  geom_point(aes(x=Date, y=nTA, fill=Precipitation), shape=21, alpha=0.5, size=1)+ 
  geom_abline(slope = 0, intercept = 2400, color="gray", linetype=2)
nTAcycle

```


```{r}
nDICcycle<-clycle  +  
  geom_smooth(aes(x=Date, y=(nDIC), colour=Zone), span= 0.3, se=FALSE)+
  geom_point(aes(x=Date, y=nDIC, fill=Precipitation), shape=21, alpha=0.5, size=1)+ 
  geom_abline(slope = 0, intercept = 2100, color="gray", linetype=2)
nDICcycle

```

```{r}
pHcycle<-clycle  +  
  geom_smooth(aes(x=Date, y=pH, colour=Zone), span= 0.3, se=FALSE)+
  geom_point(aes(x=Date, y=pH, fill=Precipitation), shape=21, alpha=0.5, size=1)+ 
  geom_abline(slope = 0, intercept = 8, color="gray", linetype=2)
pHcycle

```

```{r}
pCO2cycle<-clycle  +  
  geom_smooth(aes(x=Date, y=pCO2, colour=Zone), span= 0.3, se=FALSE)+
  geom_point(aes(x=Date, y=pCO2, fill=Precipitation), shape=21, alpha=0.5, size=1)+ 
  geom_abline(slope = 0, intercept =350, color="gray", linetype=2)
pCO2cycle

```

