# 3b. TA and DIC realtion

```{r}
TA_DIC<- ggplot(CC.data, aes (DIC, TA)) + 
  
  theme_bw() +
  scale_y_continuous(#limits = c(1700,2900),
                     #expand = c(0, 0),
                     #breaks = seq(1800, 2800, 100),
                    name="TA") +
  scale_x_continuous(# limits = c(1600, 2600),
                     # expand = c(0, 0),
                     # breaks = seq(1500,2600,100),
                      name="DIC")+
  
theme(legend.position="top",
          plot.background=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, 
                                         color = "black")
          )

#TA_DIC+ 
 #geom_point(aes (fill=Region, shape=Season), alpha=0.5)+
 #scale_shape_manual(values=c(21, 22, 23, 24))

#ggsave(file="Outputs/Figure_1_Experiment_design.svg", plot=Design, dpi = 300, width=6, height=4)
```

```{r}
TA_DIC +
  geom_point(aes (fill=Season), shape=21, alpha=0.5)+
  geom_smooth(method = "lm", colour="black")+
  facet_wrap(~Region, scales = "free")
 
```

**Figure 3b:** Linear regressions of total alkalinity (TA) as a function of disolved inorganic carbon DIC.


```{r, echo=TRUE}
 # Individual LR for each region
    TA_DIC_lm <- CC.data %>%
      group_by(Region) %>%
      do(mod = lm(TA ~ DIC, data = .))

    TA_DIC_coef <- TA_DIC_lm %>%
        do(data.frame(
        Region = .$Region,
        var = names(coef(.$mod)),
        coef(summary(.$mod)))
        )
    kable(as.data.frame(TA_DIC_coef, format = "markdown"),
          caption = "Table 3: nTA vs nDIC equations")
    
```
