---
title: "Duplicates"
author: "Ana Palacio-Castro"
date: "October 15, 2021"
output: html_document
---

```{r setup, include=FALSE}
Aragonite_year<- ggplot(Duplicates,
                          aes(x=Date, y=Aragonite_Sat_W)) +
  
  theme_bw() +
  scale_y_continuous(limits = c(0,5.5),
                       name=("Aragonite Saturation") ,
                       breaks = seq(0, 5, 1),  
                       expand = c(0, 0)) +
  ylab("Year")+
  #scale_x_date(name="Date",
               #labels = date_format("%M/%Y"),
               #limits = c(-1,114),
   #            expand = c(0, 0),
    #           breaks ="6 months")+
  
#geom_boxplot()+
geom_point(aes(fill=factor(File_Origin)), shape=21, alpha=0.5)+ 
theme(legend.position=c(0.65, 0.1),
      legend.direction = "horizontal",
      legend.title = element_blank(),
          plot.background=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          ) +
  facet_wrap(Zone~Sub_region)
  
Aragonite_year
#ggsave(file="Outputs/Aragonite.svg", plot=Aragonite, dpi = 300, width=6, height=4)
```


```{r setup, include=FALSE}
DupDIC<- ggplot(Duplicates,
                          aes(x=Date, y=nDIC)) +
  
  theme_bw() +
  #scale_y_continuous(limits = c(0,5.5),
  #                     name=("Aragonite Saturation") ,
  #                    breaks = seq(0, 5, 1),  
  #                     expand = c(0, 0)) +
  ylab("Year")+
  #scale_x_date(name="Date",
               #labels = date_format("%M/%Y"),
               #limits = c(-1,114),
   #            expand = c(0, 0),
    #           breaks ="6 months")+
  
#geom_boxplot()+
geom_point(aes(fill=factor(File_Origin)), shape=21, alpha=0.5)+ 
theme(legend.position=c(0.65, 0.1),
      legend.direction = "horizontal",
      legend.title = element_blank(),
          plot.background=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          ) +
  facet_wrap(Zone~Sub_region)
  
DupDIC
#ggsave(file="Outputs/Aragonite.svg", plot=Aragonite, dpi = 300, width=6, height=4)
```



```{r setup, include=FALSE}
TAdeu<- ggplot(Duplicates,
                          aes(x=Date, y=pH
                              )) +
  
  theme_bw() +
  #scale_y_continuous(limits = c(0,5.5),
  #                     name=("Aragonite Saturation") ,
  #                    breaks = seq(0, 5, 1),  
  #                     expand = c(0, 0)) +
  ylab("Year")+
  #scale_x_date(name="Date",
               #labels = date_format("%M/%Y"),
               #limits = c(-1,114),
   #            expand = c(0, 0),
    #           breaks ="6 months")+
  
#geom_boxplot()+
geom_point(aes(fill=factor(File_Origin)), shape=21, alpha=0.5)+ 
theme(legend.position=c(0.65, 0.1),
      legend.direction = "horizontal",
      legend.title = element_blank(),
          plot.background=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          panel.background =element_rect(fill = NA, color = "black")
          ) +
  facet_wrap(Zone~Sub_region)
  
TAdeu

```
